# Quantile normalisation

[Quantile Normalization](https://en.wikipedia.org/wiki/Quantile_normalization) is a method to align distributions. Implement it using NumPy axis-wise operations and fancy indexing.

*Hint: look for documentation for `np.sort`, and `np.argsort`.*

In [1]:
from scipy.stats import rankdata

def qnorm(x):
    """Quantile normalize an input matrix.
    
    Parameters
    ----------
    x : 2D array of float, shape (M, N)
        The input data, with each column being a
        distribution to normalize.
        
    Returns
    -------
    xn : 2D array of float, shape (M, N)
        The normalized data.
    """
    order = np.argsort(x, axis=0) # using axis argument
    ranks = np.argsort(order, axis=0)
    rank_values = np.sort(x, 0).mean(1)
    return rank_values[ranks] # broadcasting / indexing

In [2]:
import numpy as np
data = np.array([[5, 4, 3],
                 [2, 1, 4],
                 [3, 5, 6],
                 [4, 2, 7]])

In [3]:
qnorm(data)

array([[ 5.66666667,  4.66666667,  2.        ],
       [ 2.        ,  2.        ,  3.        ],
       [ 3.        ,  5.66666667,  4.66666667],
       [ 4.66666667,  3.        ,  5.66666667]])

In [4]:
results = [[5.67, 4.67, 2.00],
           [2.00, 2.00, 3.00],
           [3.00, 5.67, 4.67],
           [4.67, 3.00, 5.67]]

In [5]:
from numpy.testing import assert_array_almost_equal

assert_array_almost_equal(qnorm(data), results, decimal=2)

# Introduction

Learning objectives:

* Knows to construct an array with given or random values.
* Knows how to determine the arguments and return values from built-in documentation.
* Knows how to sort an array in numerical order and to determine the order of elements in sorted array.
* Can explain the difference between element-wise and matrix product of two arrays.
* Knows how to apply reduction functions (mean, min, max) along a given axis.
* Can find a specialised numerical algorithm from the ones available in numpy.

* array construction: array, random, eye
* array shape: shape, reshape
* array methods: mean/min/max, sort, argsort
* array operations: add/substract with arrays and scalars, element-wise multiplication, and matrix dot product
* numerical methods: fft, linalg, dot

## numpy functions

1) Create a 5x5 square array with number 5 on diagonal and zeros otherwise. Consider using `np.eye` function (you can check the docstring).

2) Generate a random sequence of 10 integers from 1 to 100 without repetition (you may want to use `np.random.rand` and `np.argsort`).

In [6]:
np.random.rand(100).argsort()[:10]

array([96, 80, 20,  9, 81, 72, 93, 99, 77, 82])

3) Solve the following system of linear equations using numpy. Test the solution.
    
$$2x_1 + 3x_2 = 3$$
$$5x_1 - x_2 = 6$$

In [7]:
a = [[2,3], [5, -1]]
b = [1, 2]
x = np.linalg.solve(a, b)
np.dot(a, x) - b

array([ -1.11022302e-16,  -2.22044605e-16])

## Axis-wide computation

1) Create a 3x4 array of random values. Compute the sum over the columns.

2) Generate a 10 x 3 array of random numbers. From each row, pick the number closest to 0.75. Make use of np.abs and np.argmax to find the column j which contains the closest element in each row.

In [8]:
x = np.random.rand(10,3)
i = np.abs(x - 0.75).argmax(1)

# Broadcasting

Learning objectives:

* Knows how to add a scalar to all elements of an array.
* Can predict the result of additions of matrices and row or column vectors.
* Can explain why broadcasting is better than using for loops.
* Understands the rules of broadcasting and can predict the shape of broadcasted arrays.
* Knows how to control broadcasting using `np.newaxis` object.

1) Calculate Z-score for each row of a 10x100 matrix.

In [9]:
X = np.random.rand(10, 100)
zscore = (X - x.mean(1)[:, None])/np.std(x,1)[:, None]

2) Below, produce the array containing the sum of every element in `x` with every element in `y`

In [10]:
x = np.random.rand(3, 5)
y = np.random.randint(10, size=8)
z = x # FIX THIS

In [11]:
z = x[:, :, None] + y[None]

3) Given the arrays:
    

In [12]:
X = np.random.rand(10,3)
Y = np.random.rand(3)

which of the following will **not** produce an error:

a) `X + Y`

b) X[None, :] + Y

c) X[np.newaxis, :] + Y

d) X[None, :] + Y[:, None]

e) X[:, np.newaxis] + Y

f) `X + Y[np.newaxis, :]`

What will be the shapes of the final broadcasted arrays? Try to guess and then check using `np.broadcast_arrays`.

In [13]:
Xb, Yb = np.broadcast_arrays(X, Y)
print(Yb.shape)

(10, 3)


4) What are the dimensionalities of `x`, `y` and `z` in the two cases:

```
x, y = np.mgrid[:10, :5]
z = x + y
```

and 

```
x, y = np.ogrid[:10, :5]
z = x + y
```

What might be the advantage of using `np.ogrid` over `np.mgrid`?

6) Calculate an outer product using broadcasting?

# Indexing

Learning objectives:

* Can get the value of any element of a N-dimensional array knowing its row, column etc. indices.
* Can use slices to get and modify ranges of elements.
* Can explain the difference between a copy and a view. Knows which methods of indexing return a copy or view.
* Knows how to select elements from an array based on some criteria applied to their values.
* Can obtain a sub-array of non-contigeous of elements using fancy indexing.
* Can combine axis-based reductions, broadcasting and indexing to implement simple clustering algorithms.
* Understands what are the advantages of vectorisation and when to use or not use it.

## Simple indexing and slicing

Let `x = np.array([1, 5, 10])`.

Which of the following will show [1, 10]:

a) `print(x[::2])`

b) `print(x[[0, 2]])`

c) `x[1, 3]`

d) `x[[1, -1]]`

3) Create a 3x4 array of
random values (using `np.random.rand`), and call it ``x``.
Create another array as follows: ``y = x[2]``.
What happens when you modify ``y`` &mdash; does ``x`` also change? Now try `y = x[:2]` and modify it's first element. What happens now?

4) Create a 8x8 matrix and fill it with a checkerboard pattern

## Boolean indexing

1) Rectify an array with random numbers from normal distribution (generated with `np.random.randn`) using boolean indexing.

In [14]:
x = np.random.randn(100)
x[x<0] = 0

2) Select odd elements from an integer array.

## Fancy indexing

1) Select randomly with repetition 10 elements from an array of 100 elements.

In [15]:
x = np.random.rand(100)
i = np.random.randint(0, 100, 10)
x[i]

array([ 0.82324748,  0.25327442,  0.60165156,  0.43506678,  0.98990766,
        0.00482431,  0.05298637,  0.61761686,  0.71093484,  0.52197775])

2) Implement K-means algorithm.

5) Predict and verify the shape of the following slicing operation.

```python
x = np.empty((10, 8, 6))

idx0 = np.zeros((3, 8)).astype(int)
idx1 = np.zeros((3, 1)).astype(int)
idx2 = np.zeros((1, 1)).astype(int)

x[idx0, idx1, idx2]
```

# Array container

Learning objectives:

* Can list some of the objects which can be contained in an array.
* Understands the concept of `dtype` and can select `dtype` best for the data at hand.
* Knows what is an object array and when it is created.
* Can explain what are `ndim`, `shape` and `stride` properties of an array.
* Understand the layout of an array in memory and knows how to use it for best array performance.
* Can explain the difference between Fortran- and C-based order. Knows the default.

## dtype

1) Construct the array `x = np.array([0, 1, 2, 3], dtype=np.uint8)` (here, `uint8`
represents a single byte in memory, an unsigned integer between 0 and 255). Can
you explain the results obtained by x + 1 and x / 2? Also try `x.astype(float) + 1` and `x.astype(float) / 2`.

2) What is the dtype of the following arrays?


In [16]:
a = np.array([[1], 
              [2,3],
              [4,5,6]])
b = np.array(['a', 'b', 'c'])
c = np.array([1, 2., 3.])
d = np.array([np.dot, np.array])

In [17]:
d.dtype

dtype('O')

3) Imagine you have a list of names and scores, which you want to store in numpy array. Construct a dtype such that the following works. Look at documentation of `np.dtype`.

In [18]:
np.array([('Bartosz', 5), ('Nelle', 4)], dtype=[('string', 'S40'), ('number', np.int)])

array([('Bartosz', 5), ('Nelle', 4)], 
      dtype=[('string', 'S40'), ('number', '<i8')])

## Memory layout

- Create 3x4 random array. Have a look at its different properties: ``x.shape``, ``x.ndim``,
``x.dtype``, ``x.strides``. What does each property tell you about the array?

- Compare the strides property of x.T to the above. What is x.T and can you
explain the new strides?

- What is the maximum number of dimensions a NumPy array can have? Use one of the
array constructors (np.zeros, np.empty, np.random.random, etc.) to find out.m

3) Compare the time of summing over rows and columns. How would you explain the differences?

In [19]:
A = np.random.rand(10, 100000)

In [20]:
%timeit A.sum(0)

1000 loops, best of 3: 890 µs per loop


In [21]:
A = np.random.rand(100000, 10)

In [22]:
%timeit A.sum(1)

1000 loops, best of 3: 1.85 ms per loop


1) Use `as_strided` to produce a sliding-window view of a 1D array.

In [23]:
def sliding_window(arr, size=2):
    """Produce an array of sliding window views of `arr`
    
    Parameters
    ----------
    arr : 1D array, shape (N,)
        The input array.
    size : int, optional
        The size of the sliding window.
        
    Returns
    -------
    arr_slide : 2D array, shape (N - size - 1, size)
        The sliding windows of size `size` of `arr`.
        
    Examples
    --------
    >>> a = np.array([0, 1, 2, 3])
    >>> sliding_window(a, 2)
    array([[0, 1],
           [1, 2],
           [2, 3]])
    """
    return arr  # fix this

In [24]:
# test your code
sliding_window(np.arange(8), 3)

array([0, 1, 2, 3, 4, 5, 6, 7])

2) The `order` keyword of some `numpy` functions determines how two- or more dimensional arrays are laid out in the memory. If order is 'C', then the array will be in C-contiguous order (last-index varies the fastest). If order is 'F', then the returned array will be in Fortran-contiguous order (first-index varies the fastest). In what order will be the 2D array stored in memory? (*Hint*: You can use `np.ravel(x, order='A')` to test it).

In [25]:
x = np.array([[1, 2, 3], [4, 5, 6]], order='F')
print(x)
np.ravel(x, order='A')

[[1 2 3]
 [4 5 6]]


array([1, 4, 2, 5, 3, 6])

4) Explain how broadcasting works internally using the example below. What will be shapes and strides of `x` and `y` after broadcasting. Test it using `np.broadcast_arrays` in the following example and look at `strides` and `shape` properties of both arrays.

In [26]:
x = np.random.rand(5,10)
y = np.random.rand(10)
z = x + y

In [27]:
xb, yb = np.broadcast_arrays(x,y)

In [28]:
yb.strides

(0, 8)

More exercies: https://github.com/rougier/numpy-100

Calculate pairwise distances between major European cities

In [31]:
import numpy as np
coords = np.recfromcsv('cities.csv')

In [33]:
names = coords['name']
coordinates = coords[['x', 'y']]

In [36]:
coordinates

rec.array([(4.9, 52.3666666667), (23.7166666667, 37.9666666667),
 (13.3833333333, 52.5166666667), (-0.1275, 51.5072222222),
 (-3.71666666667, 40.3833333333), (10.75, 59.95), (2.3508, 48.8567),
 (12.5, 41.9), (21.0166666667, 52.2333333333)], 
          dtype=[('x', '<f8'), ('y', '<f8')])

In [40]:
coords = coordinates.view('f8').reshape(-1, 2
                            )

In [43]:
np.array(coords)

array([[  4.9       ,  52.36666667],
       [ 23.71666667,  37.96666667],
       [ 13.38333333,  52.51666667],
       [ -0.1275    ,  51.50722222],
       [ -3.71666667,  40.38333333],
       [ 10.75      ,  59.95      ],
       [  2.3508    ,  48.8567    ],
       [ 12.5       ,  41.9       ],
       [ 21.01666667,  52.23333333]])

In [44]:
names

array(['Amsterdam', 'Athens', 'Berlin', 'London', 'Madrid', 'Oslo',
       'Paris', 'Rome', 'Warsaw'], 
      dtype='|S9')

In [65]:
coords = np.array([
                   [ 23.71666667,  37.96666667],
                   [ 13.38333333,  52.51666667],
                   [ -0.1275    ,  51.50722222],
                   [ -3.71666667,  40.38333333],
                   [  2.3508    ,  48.8567    ],
                   [ 12.5       ,  41.9       ]])

names = np.array(['Athens', 'Berlin', 'London', 'Madrid', 'Paris', 'Rome'])

R= 6371.009 


In [67]:

rad = coords / 180 * np.pi
R * np.sqrt(np.sum((rad[:, None, :] - rad[None, :, :]) ** 2, 2))

array([[    0.        ,  1984.38921474,  3049.03920643,  3062.26507472,
         2666.5802537 ,  1321.70090479],
       [ 1984.38921474,     0.        ,  1506.5255377 ,  2331.46096707,
         1292.50664605,  1184.60026382],
       [ 3049.03920643,  1506.5255377 ,     0.        ,  1299.71319778,
          403.49015659,  1764.30010767],
       [ 3062.26507472,  2331.46096707,  1299.71319778,     0.        ,
         1158.84321043,  1811.08275581],
       [ 2666.5802537 ,  1292.50664605,   403.49015659,  1158.84321043,
            0.        ,  1368.20539888],
       [ 1321.70090479,  1184.60026382,  1764.30010767,  1811.08275581,
         1368.20539888,     0.        ]])

In [76]:
mean_lat = (rad[:, None, 1] + rad[None, :, 1]) / 2
dist = (rad[:, None, :] - rad[None, :, :])
corr = np.dstack((mean_lat, np.zeros(mean_lat.shape)))
R * np.sqrt(np.sum((dist * np.cos(corr))**2, 2))

array([[    0.        ,  1808.89836354,  2411.23928333,  2379.99096328,
         2108.28716907,  1051.63573237],
       [ 1808.89836354,     0.        ,   931.47263743,  1880.56443644,
          877.33115374,  1182.40538538],
       [ 2411.23928333,   931.47263743,     0.        ,  1267.67013577,
          343.5151412 ,  1438.19247125],
       [ 2379.99096328,  1880.56443644,  1267.67013577,     0.        ,
         1057.51822014,  1368.40531072],
       [ 2108.28716907,   877.33115374,   343.5151412 ,  1057.51822014,
            0.        ,  1107.59808129],
       [ 1051.63573237,  1182.40538538,  1438.19247125,  1368.40531072,
         1107.59808129,     0.        ]])